### ISSUE TITLE
Completeness?

### ISSUE THREAD

**Issue by jbenet** [ipfs/py-ipfs-http-client#42]
What is the completeness of this api? in relation say to https://github.com/ipfs/js-ipfs-api ?

Many people are using ipfs from python and they've asked me this question lots. I think it would be good to have a spec completeness markdown checklist.

**Comment by whereswaldon** [comment]
As far as I am aware, this is where things are. This is drawn from [here](https://github.com/ipfs/specs/blob/master/public-api/core/README.md).

There were a few items in the spec that I'm not sure how to implement (node_start and node_stop), and a few that people on IRC said to hold off on because they might have security implications.

### Core

- [x] version
- [ ] node
  - [x] id
  - [ ] start - not implemented due to unclear spec
  - [ ] stop - not implemented due to unclear spec
- [x] block
  - [x] get
  - [x] put
  - [x] stat
- [x] object
  - [x] data
  - [x] get
  - [x] links
  - [x] new
  - [x] patch
  - [x] put
  - [x] stat
- [x] refs
  - [x] local
- [ ] repo
  - [ ] init - not implemented due to security concerns
  - [x] stat
  - [x] gc
  - [ ] config get - not implemented due to security concerns
  - [ ] config put - not implemented due to security concerns
- [x] pin
  - [x] add
  - [x] ls
  - [x] rm

### Extensions

- [ ] name (ipns)
  - [ ] name publish
  - [ ] resolve
- [ ] dns
  - [ ] resolve
- [ ] tar
  - [ ] add
  - [ ] cat
- [ ] tour
  - [ ] list
  - [ ] next
  - [ ] restart
- [x] files
  - [x] add - see #49 
  - [x] cat
  - [x] get - see #48
- [ ] stat
  - [ ] bw
- [ ] mount
- [ ] bootstrap
  - [ ] add
  - [ ] list
  - [ ] rm
- [ ] bitswap - see #47 
  - [ ] stat
  - [ ] unwant
  - [ ] wantlist
- [x] log
  - [x] level
  - [x] tail

**Comment by whereswaldon** [comment]
Actually, the above is a checklist from the wrong API? I'm confused about the discrepancies between [this](http://docs.ipfs.apiary.io/#reference/bitswap/get) and [this](https://github.com/ipfs/specs/blob/master/public-api/core/README.md).
@jbenet What is the difference in intention between those two specs?

### Here is the functionality of `py-ipfs-api` compared against the Apiary:

**NOTE**: Not all of the following are tested currently.
- [x] add
- [ ] bitswap
  - [ ] stat
  - [ ] wantlist
  - [ ] unwant
- [x] block
  - [x] get
  - [x] put
  - [x] stat
- [ ] bootstrap
  - [x] add
  - [ ] list
  - [x] rm
- [x] cat
- [ ] commands
- [x] config
  - [x] config
  - [x] replace
  - [x] show
- [x] dht
  - [x] findpeer
  - [x] findprovs
  - [x] get
  - [x] put
  - [x] query
- [ ] diag
  - [ ] cmds
  - [ ] cmds clear
  - [ ] cmds set-time
  - [ ] net
  - [ ] sys
- [x] dns
- [x] file ls
- [ ] files
  - [x] rm
  - [ ] flush
  - [x] mv
  - [x] cp
  - [x] ls
  - [x] mkdir
  - [x] stat
  - [x] read
  - [x] write
- [x] get
- [x] id
- [x] log
  - [x] level
  - [x] ls
  - [x] tail
- [x] ls
- [x] name
  - [x] publish
  - [x] resolve
- [ ] object
  - [x] data
  - [ ] diff
  - [x] get
  - [x] links
  - [x] new
  - [x] patch append-data
  - [x] patch add-link
  - [x] patch rm-link
  - [x] patch set-data
  - [x] put
  - [x] stat
- [x] pin
  - [x] add
  - [x] ls
  - [x] rm
- [x] ping
- [x] refs
  - [x] refs
  - [x] local
- [ ] repo
  - [ ] fsck
  - [x] gc
  - [ ] stat
  - [ ] verify
  - [ ] version
- [x] resolve
- [ ] stats
  - [ ] bitswap
  - [ ] bw
  - [ ] repo
- [ ] swarm
  - [x] addrs
  - [ ] addrs local
  - [x] connect
  - [x] disconnect
  - [ ] filters
  - [x] filters add
  - [x] filters rm
  - [x] peers
- [ ] tar
  - [ ] add
  - [ ] cat
- [ ] tour
  - [ ] tour
  - [ ] list
  - [ ] next
  - [ ] restart
- [ ] update
- [x] version

And some pythonic candy:

- [x] add str
- [x] add json
- [x] get json
- [x] add pyobj
- [x] get pyobj

**Comment by jbenet** [comment]
cc @diasdavid @RichardLitt they can maybe explain more.

**Comment by diasdavid** [comment]
@whereswaldon with regards to bitswap, they both list the same commands, care to list what is the discrepancy you see?

Another great resource to help is: https://github.com/ipfs/interface-ipfs-core, we have a bunch of the API defined at https://github.com/ipfs/interface-ipfs-core/tree/master/API and with tests (for js, but that can be translated to python, here https://github.com/ipfs/interface-ipfs-core/tree/master/src). Currently, both js-ipfs and js-ipfs-api follow this interface.

**Comment by whereswaldon** [comment]
@diasdavid Not with regards to bitswap, but in general. Both of those seem like feature inventories, but not necessarily the same features. One lists "files add", "files get", and "files cat" while the other has "get", "add", "cat" a tons of different commands under the "file" and "files" namespaces. They just don't seem to align, and I don't understand why.

I'll take a look at those tests. It would be nice to port them to Python. Thank you!

**Comment by diasdavid** [comment]
The "files" is a specific case, see: https://github.com/ipfs/specs/issues/98
