### ISSUE TITLE
Project Infrastructure Goals

### ISSUE THREAD

**Issue by whereswaldon** [ipfs/py-ipfs-http-client#60]
I'd like to lay out some short-term objectives for this repo to get everyone's opinions about them. Some of them might not be great ideas, and I'd like to have that pointed out before I spend any energy on them.
### Concrete Objectives
- [ ] Get 100% test coverage **and** enforce it with CI
- [ ] Implement more of the HTTP API Spec
- [ ] Implement and enforce commit message standards (like signing off with name/license)
- [x] Rename PIP package and python module to be called `ipfsapi`
### Fuzzy Objectives
- [ ] Integrate project with Codacy for better code insight
- [x] Develop "good" documentation (Docstring and pydoc, I think)
- [ ] Create a better developer on-ramp (add a CONTRIBUTING.md with good instructions for setting up the py-ipfs-api development environment)
### Social Objectives
- [ ] Have at least two people review the code for PRs before merging them (this requires critical mass in contributors)

Thoughts? Additions? I'd love some feedback.

**Comment by jbenet** [comment]
All this LGTM! 👍

**Comment by alexander255** [comment]
I have another thing that I noticed while working on #63:
Currently our exception handling/raising behaviour is all over the place and entirely undocumented, this leads to downstream projects catching [errors from our underlying libraries](https://github.com/oduwsdl/ipwb/commit/60936e5308c9a0be1e6278ae76f7449fa70aea73), because it's the most reliable thing they can currently do.

Basically we need:

  1. A list of exceptions (within reasonable limits) that we expect our underlying libraries to raise (things like connection and protocol errors mostly)
  2. Exception handling code that will consistently catch and wrap these errors at the appropriate locations
  3. Extra documentation in the `Client` API about which exceptions may be expected at each call (or probably ratter a separate section since the list will be very similar between all calls)
  4. Hopefully some documentation in the internal APIs as well
